### ISSUE TITLE
firewall changes are not working right

### ISSUE THREAD

**Issue by alfredodeza** [Azure/postgresql#24]
After creating a PostgreSQL DB on Azure, going through the various credential steps and adding the secrets, I couldn't get the workflow step to work with this action, receiving a:

```
Azure Postgres: no pg_hba.conf entry for host "x.x.x.x", user "xxxxxx", database postgres, SSL on"
```

I've removed the IP's from the error report. Was not able to connect to the database. I restarted the server a couple of times as it was suggested that might help with pg_hba.conf entries to no avail.

At desperation, I opened up the database firewall manually to any/all IPs and the action was finally able to connect.

I no longer have access to the GH logs, but I do recall seeing output from the action making changes to the firewall correctly. In the Azure portal for the postgresql DB it does show: "Update firewall rule create" and "Delete firewall Rule"

The following is the full YAML file [from this repo](https://github.com/alfredodeza/scraping-demo/blob/main/.github/workflows/main.yml)

```yaml
name: ExploitDB and CVE scraping

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: run scrapy 
        run: scrapy crawl exploit
        working-directory: cve
        
      - uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - uses: azure/postgresql@v1
        with:
          connection-string: ${{ secrets.AZURE_POSTGRESQL_CONNECTION_STRING }}
          server-name: exploit-db.postgres.database.azure.com
          plsql-file: "sql_files/*.sql"
```
